// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CliTokens defines model for CliTokens.
type CliTokens struct {
	AccessToken  string `json:"AccessToken"`
	RefreshToken string `json:"RefreshToken"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	Handle string `json:"Handle"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"Error"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	Ok bool `json:"ok"`
}

// OtpLoginRequest defines model for OtpLoginRequest.
type OtpLoginRequest struct {
	// Otp One-time pairing code displayed at /cli/login.
	Otp string `json:"Otp"`
}

// RefreshTokenHeader defines model for RefreshTokenHeader.
type RefreshTokenHeader = string

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	XRefreshToken RefreshTokenHeader `json:"X-Refresh-Token"`
}

// RefreshTokensParams defines parameters for RefreshTokens.
type RefreshTokensParams struct {
	XRefreshToken RefreshTokenHeader `json:"X-Refresh-Token"`
}

// OtpLoginJSONRequestBody defines body for OtpLogin for application/json ContentType.
type OtpLoginJSONRequestBody = OtpLoginRequest
